### ISSUE TITLE
Save to file

### ISSUE THREAD

**Issue by 89z** [moon004/Go-deezer-downloader#13]
currently standard output is used:

https://github.com/moon004/Go-deezer-downloader/blob/fdfac3f112003a4ce4730a79fe2c0dae38d5796c/Utils.go#L175

this can be a problem on Windows, as redirects add carriage returns

**Comment by 89z** [comment]
https://github.com/moon004/Go-deezer-downloader/pull/14

**Comment by moon004** [comment]
@89z 
Sorry for the late reply, the reason i wanted to stream to standard output is because it is for vm used, maybe we could create another branch, for this version, that we stream the output to a file, or also we can branch out a version that is for windows.

**Comment by 89z** [comment]
https://github.com/moon004/Go-deezer-downloader/pull/15
