### ISSUE TITLE
Explanation about download of playlist

### ISSUE THREAD

**Issue by ouatrahim** [moon004/Go-deezer-downloader#5]
Hey really awesome work ! 
But i would like to know how to download a playlist? 
I saw in source code that there is playlist parameters but i could not find how to make it work

**Comment by moon004** [comment]
Sry, could you show me which playlist parameters? Sry for the late reply but for now this project will be under maintenance mode as there is a change in Deezer server's API. I will patch things up in the near future, so stay tune.

Thanks for trying things out.
