### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by doronbehar** [moon004/Go-deezer-downloader#6]
2 Issues:

Using latest `master`, `go.mod` and `go.sum` were updated after `go build`:

```diff
diff --git i/go.mod w/go.mod
index 882fb66..d261a0c 100644
--- i/go.mod
+++ w/go.mod
@@ -1,3 +1,6 @@
 module github.com/go-decrypt-deezer
 
-require golang.org/x/crypto v0.0.0-20181112202954-3d3f9f413869
+require (
+	github.com/pkg/errors v0.8.1
+	golang.org/x/crypto v0.0.0-20181112202954-3d3f9f413869
+)
diff --git i/go.sum w/go.sum
index 0eaa3a7..254601a 100644
--- i/go.sum
+++ w/go.sum
@@ -1,2 +1,4 @@
+github.com/pkg/errors v0.8.1 h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
+github.com/pkg/errors v0.8.1/go.mod h1:bwawxfHBFNV+L2hUp1rHADufV3IMtnDRdf1r5NINEl0=
 golang.org/x/crypto v0.0.0-20181112202954-3d3f9f413869 h1:kkXA53yGe04D0adEYJwEVQjeBppL01Exg+fnMjfUraU=
 golang.org/x/crypto v0.0.0-20181112202954-3d3f9f413869/go.mod h1:6SG95UA2DQfeDnfUPMdvaQW0Q7yPrPDi9nlGo2tz2b4=
```

No big deal though. Besides that, I get an error when running:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.DecryptDownload(0x0, 0x0, 0xc00036c2a0, 0x9, 0x6f2c2f, 0x1, 0x908754, 0x1, 0x0, 0xc00017bb10, ...)
	/var/src/Go-deezer-downloader/Utils.go:121 +0x652
main.GetUrlDownload(0x7fffa249720d, 0x9, 0xc00009ac60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/src/Go-deezer-downloader/main.go:185 +0xcfc
main.main()
	/var/src/Go-deezer-downloader/main.go:30 +0x7c
```

The usertoken is supposed to be very long right (416 characters) right?

**Comment by moon004** [comment]
No, the `usertoken` is actually 192 characters long. [Here is the guide on how to obtain the token](https://notabug.org/RemixDevs/DeezloaderRemix/wiki/Login+via+userToken).

**Comment by doronbehar** [comment]
I read the instructions. Could you recheck please perhaps Deezer has increased the size of this variable? For sure it's 416 for me.

**Comment by moon004** [comment]
i just checked it was 192 characters long, with both chrome and firefox, anyway, my [web app](http://hopesndreams.s3-website.ap-northeast-1.amazonaws.com/) backend is running on this application and is working fine, and the `usertoken` is 192 characters long, i'm assuming u are taking the cookie value of `arl`. I suppose maybe deezer provide token based on which country you from?

By the way, i'm glad you try this application out.

**Comment by doronbehar** [comment]
I'm from Israel, maybe it's because I logged in relatively recently and the old tokens are still backwards compatible? Maybe you should try log in to deezer through "incognito" or whatever your browser calls it and check there?

**Comment by moon004** [comment]
Yep i tried that, it is still the same, 192 characters long...

**Comment by doronbehar** [comment]
Hmm funny, don't know why it was longer and different before.. Thanks anyway!

**Comment by moon004** [comment]
Soo, do you still get the same error?

**Comment by doronbehar** [comment]
No.

**Comment by doronbehar** [comment]
It works*.
